apiVersion: apps/v1
kind: Deployment
metadata:
  name: nrsa-atd-deployment
spec:
  replicas: 3
  template:
    metadata:
      name: nrsa-atd
      labels:
        app: nrsa-atd
        type: backend
    spec:
      containers:
        - name: spring-boot-test
          image: luinabaro/spring-boot-test
  selector:
    matchLabels:
      app: nrsa-atd
      type: backend
