apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-test-deployment
spec:
  replicas: 3
  template:
    metadata:
      name: spring-boot-test
      labels:
        type: spring-boot-api
    spec:
      containers:
        - name: spring-boot-test
          image: luinabaro/spring-boot-test
  selector:
    matchLabels:
      type: spring-boot-api
